import pathlib,json,csv,collections,re
O=pathlib.Path(__file__).resolve().parent
rs=json.loads((O/'registros.json').read_text()); es=json.loads((O/'entradas.json').read_text()); ps=json.loads((O/'publicacion-r2.json').read_text())
notes={
'01808acbd270':'Leídas pp3–7: criterios de cuestiones, fuente, tema y texto; orientaciones y temario. No dan respuestas concretas. false correcto.',
'053608cf06ee':'Leídas pp1–2 de criterios oficiales valencianos: comentario, morfología, sintaxis, cohesión, adecuación, literatura y descuentos. No hay soluciones concretas. false correcto.',
'070c3795d83c':'Leídas pp1–4: tablas y escalas de evaluación para apartados A/B; las imágenes 1/2/3 son productos a evaluar, no soluciones propuestas. false correcto.',
'0a50595f8036':'Leídas pp2–3: criterios de boceto/dibujo final y orientaciones. La p3 lleva SOLUCIONES, pero contiene un temario, no dibujos resueltos. false correcto.',
'0bed555f767c':'Leída p3: criterios de comprensión, morfosintaxis y redacción italiana, sin respuestas. false correcto; no se inventan textos italianos.',
'0d5e5806192a':'Leídas pp3–4: estructura de Lengua y criterios generales de todas las preguntas; no hay solucionario concreto. false correcto.',
'0fedaac3fe5f':'Leídas pp1–2: criterios generales valencianos y penalizaciones; no hay respuestas. false correcto.',
'13244a0fa596':'Leídas pp3–8: criterios de Historia, orientaciones y programa. No respuestas específicas de ese examen. false correcto.',
'172579fa76d4':'Leídas pp6–7: rúbricas graduadas de Filosofía, bloques1/2. No respuesta filosófica concreta; false correcto.',
'17445f0ab770':'Leída p1 bilingüe es/va: seis reglas generales de Química. No resultados químicos. false correcto.',
'09feb8541d90':'12 respuestas castellanas de academia: documentos Cádiz/franquismo, cuatro conceptos, medidas legislativas, ideología, constituciones y mujer. Cotejo léxico íntegro contra pp1–11 y atribución de todos los nodos por pregunta/tema. No versión valenciana en la fuente. n3 referencia p2 aunque comienza p1.',
'16d0161b5c29':'12 respuestas castellanas de academia: Trienio, Riego, sufragio/Segunda República, cuatro conceptos y comparaciones. Cotejo léxico íntegro pp1–11 y atribución por encabezados/enunciados. Sin traducción valenciana añadida ni omisión textual grande detectada.',
'1b0c55921d01':'12 respuestas castellanas de academia: Inquisición, Trienio, Juan Carlos, Transición y cuatro conceptos. Cotejo léxico íntegro pp1–8 y atribución por preguntas/temas. n16 apunta p7 aunque empieza p6. No versión valenciana inventada.',
'334e3227bf82':'12 respuestas castellanas de academia: Constitución1812/FernandoVII, huelga1917/Primo, cuatro conceptos y temas constitucionales/sociales. Cotejo léxico íntegro pp1–9 y atribución por encabezados. Cuatro conceptos n8–n11 correctos en s1 desaparecen de publicación.',
'6426459db740':'20 respuestas castellanas de academia:12 cuestiones,2 fuentes históricas con2 apartados cada una,1 tema,3 comentarios. Cotejo léxico íntegro pp1–12; correspondencia por A/B y enunciado. Texto con errores históricos ya presentes en fuente; la auditoría no los atribuye a Luna ni certifica exactitud histórica.',
'0743849de2d6':'6 entradas verificadas contra pp5–6: tema, tipo textual,2 análisis sintácticos,regeneración y antónimos. Se omiten respuestas abiertas porque fuente no las resuelve.2 respuestas son solo marcador de figura; esquema cumple s1 pero no conserva análisis.',
'114bff1bacb1':'8 entradas contrastadas con pp5–6, ambas renderizadas: temas/tipos A/B,morfología,antónimos y2 árboles sintácticos. Árboles convertidos en etiquetas sin relaciones. Fuente morfológica plural contradice enunciado singular y no hay incidencia.',
'0b7e227a5499':'13 respuestas de pp5–6 cotejadas textual y visualmente: dron,función par,integral,binomial/normal,matrices,Bolzano y continuidad. Fórmulas/resultados de las13 conservados. Solución4.2 a/b p6 completamente perdida: no existe nodo p5 y sin_correspondencia vacío.',
'184bfaad518f':'9 respuestas B de p6 cotejadas visualmente, incluida barra de complemento; p5 completa renderizada. Pipeline entrega desde6 y omite12 apartados A de p5. n31 pierde complemento de M e inventa incidencia sobre errata de fuente.',
'1bc800a06e3b':'20 respuestas contrastadas íntegramente con pp6–7 renderizadas: acciones,área,recta/plano,normal,sistema,derivadas/integral,planos y probabilidad. Incluidas barras de complemento correctas en B4. No cambio matemático sustancial detectado; corrige pequeñas erratas tipográficas de fuente sin avisar.',
'2787fc4d640f':'34 apartados contrastados textual y visualmente pp4–5: enlace/Lewis,solubilidad,ácidos,orgánica,electrolisis,átomos,cinética,redox/equilibrio. Fórmulas,cargas,coeficientes,resultados y tablas revisados. Lewis solo marcador; K→k y corchete sobrante corregidos; tres incidencias de salida comprobadas.',
'32384d10aa13':'16 respuestas castellanas de pp4–7:12 cuestiones,2 fuentes,tema Transición y comentario Mendizábal. Cotejo léxico completo y atribución por A/B y contenido. n15/n16 citan p5 pero están íntegramente en p6, confirmado visual.',
'3c134e1125e6':'9 nodos con18 textos es/va contrastados pp1–6:4 conceptos,2 fuentes,2 temas y comparación agraria. Correspondencias correctas; n9 es empieza p4 y cita5; n13 va traduce Fernando→Ferran; otras regularizaciones valencianas incumplen literalidad estricta.',
'49e9ef3c3296':'14 entradas pp1–3 cotejadas textual y visualmente: sistema/productores,cúbica,probabilidad,geometría,integral y área. Árbol de probabilidad p1 omitido sin marcador; definición de x/y/z ausente de n2. Gráfica5B representada por marcador n18. Resultados de14 entradas conservados.',
'25fcf7208b8f':'21 entradas contrastadas con las9 páginas manuscritas renderizadas: discusión/sistema,derivadas/integral,recta/plano,binomial-normal,edades,Bolzano/área,rectas y Bayes.3 errores numéricos/léxicos visibles y síntesis sistemática de pasos;2 errores matemáticos graves n7/n15; erratas fuente n5,n14,n26 reconocidas.'}
findings=[]
def add(code,sev,doc,nodes,pages,kind,source,output,impact,status='confirmado'):
 findings.append(dict(id=code,severidad=sev,documento=doc,nodos=nodes,paginas_fuente=pages,tipo=kind,estado=status,evidencia_fuente=source,evidencia_salida=output,impacto=impact))
add('S01','alta','184bfaad518f',['n31'],[6],'error matemático e incidencia falsa','P(A∩M̄)=P(A)−P(A∩M)=…=0.15; la barra sobre M está visible en el PDF.','P(A\\cap M)=P(A)-P(A\\cap M); incidencia afirma que la igualdad contradictoria está impresa y se transcribió literalmente.','Cambia varón por mujer y atribuye falsamente el error a la fuente. Se publica así.')
add('S02','alta','25fcf7208b8f',['n7'],[3],'error matemático','Recuadro manuscrito 1/(2·raíz cuarta de e)−1/(2e). También paso previo e^(-1/2²).','1/(2\\sqrt e)-1/(2e).','Pierde índice4 de raíz, cambia resultado integral. Se publica así.')
add('S03','alta','25fcf7208b8f',['n15'],[5],'error matemático','Corrección continuidad69,5; numerator69,5−55,4; z>2,23; resultado0,0129.','67,5 en las dos apariciones; conserva z>2,23 y0,0129.','La cadena numérica deja de ser consistente y no avisa. Se publica así.')
add('S04','alta','184bfaad518f',['n3','n4','n5','n6','n8','n9','n10','n12','n13','n14','n16','n17'],[5],'recorte de fuente en pipeline','Página5: SOLUCIONES OPCIÓN A, ejercicios1a–d,2a–c,3a–c,4a–b.','fuente.desde=6; solo9 entradas de B.','12 soluciones no llegan al modelo s1. No es una omisión imputable al modelo sobre el PDF recibido; banco deja A sin solución.')
add('S05','alta','0b7e227a5499',[],[6],'omisión por árbol incompleto y falta de incidencia','4.2 a: matrices, casos λ∉{−1,4},λ=−1,λ=4; b: (16/5,−3/5,0)+t(1,−3,−5).','p5 no tiene pregunta4.2; s1 ni entradas ni sin_correspondencia.','Dos respuestas desaparecen de forma silenciosa. s1 debió registrarlas sin correspondencia aunque p5 carezca del nodo.')
add('S06','alta','334e3227bf82',['n8','n9','n10','n11'],[5,6],'pérdida en publicación','Solucionario define Soberanía,Absolutismo,Huelga revolucionaria,Golpe de Estado; s1 tiene las4 respuestas.','datos/preguntas.json publica8 preguntas del documento y ninguna de las4 definiciones.','p5 clasifica conceptos como apartados del bloque n7 sin pregunta. Publicación los descarta. No es un fallo s1.')
add('S07','media','114bff1bacb1',['n17','n18'],[5,6],'pérdida de estructura visual','Árboles sintácticos con líneas que asocian palabras a sintagmas y funciones.','Listas Etiquetas del esquema y secuencias \\quad; no figura ni correspondencias.','Las etiquetas sueltas no representan el análisis sintáctico. Incumple instrucción de sustituir figuras por marcador; un recorte sería necesario para recuperar la respuesta completa.')
add('S08','media','32384d10aa13',['n15','n16'],[6],'página errónea','Reyes Católicos (3) y CarlosI (4) íntegramente en p6.','Ambos entradas paginas.es=5.','Referencia lleva a una página sin esa respuesta. Exportado sin cambio.')
add('S09','baja','09feb8541d90',['n3'],[1,2],'página de continuación','La respuesta Documentos3y4 empieza al final de p1 y sigue en p2.','paginas.es=2.','Referencia parcial, no inicio. El esquema solo permite una página y no explicita inicio; no se computa como página totalmente equivocada.')
add('S10','baja','1b0c55921d01',['n16'],[6,7],'página de continuación','Comparación absolutismo/liberalismo empieza en p6 y continúa p7.','paginas.es=7.','Referencia pierde inicio; el texto completo sí está transcrito.')
add('S11','baja','3c134e1125e6',['n9'],[4,5],'página de continuación','La segunda (2.2)… Madoz… empieza al pie de p4 y continúa p5.','paginas.es=5; va=2 correcto.','Referencia castellana pierde el inicio; texto completo presente.')
add('S12','media','25fcf7208b8f',['n2','n3','n5','n9','n10','n13','n16','n19','n20','n22','n23','n24'],list(range(1,9)),'síntesis y paráfrasis','Matrices A/B explícitas en A1 p1,eliminación por filas en B1 p6,desarrollos numéricos y frases manuscritas.','A1 omite matrices; B1 salta de sistema a De las ecuaciones se obtiene; n13 dice tenemos un consejero donde fuente dice consejo.','No cumple transcripción literal ni conservación de todos los pasos aunque muchos resultados coincidan.')
add('S13','media','49e9ef3c3296',['n2','n8','n9'],[1,2],'omisión de contexto de solución','Primer ejercicio define x,y,z como número de recipientes de cada productor. Tercer ejercicio incluye árbol completo con eventos E,H,R,A,M y probabilidades.','n2 solo sistema; n8/n9 solo cálculo en p2; sin entrada para árbol ni marcador.','Solución incompleta; árbol aporta0,5 puntos según criterios p5. El criterio de puntuación no debía ir en respuesta, pero el paso gráfico sí debía estar indicado.')
add('S14','baja','3c134e1125e6',['n8','n13'],[1,2],'regularización o traducción','n8va Primera Guerra Carlista; n13va Amb la mort de Fernando VII; en es quals.','n8va Primera Guerra Carlina; n13va Ferran VII; en els quals.','Cambios semánticamente próximos pero prohibidos por no traduzcas/no corrijas; no equivalen a alucinación extensa.')
add('S15','baja','114bff1bacb1',['n20'],[1,5],'contradicción fuente/enunciado no registrada','Enunciado pregunta generalización singular; solucionario analiza General+iz+a+cion+es con morfema flexivo número.','s1 conserva es y plural,incidencias vacío.','No es invención del plural por Luna. Falta avisar de discordancia de la fuente como exige s1.')
add('S16','limitación','0743849de2d6',['n10','n11'],[5,6],'figura perdida por contrato','Dos análisis sintácticos gráficos con notas explicativas.','Solo (ver figura en la solución original).','Cumple regla s1, pero alumno no ve análisis ni recorte. Fuente original conserva la respuesta.')
add('S17','limitación','2787fc4d640f',['n5'],[4],'figura perdida por contrato','Estructuras de Lewis de Cl2 y NH3 con electrones no enlazantes.','Solo (ver figura en la solución original).','Cumple s1; esquema no guarda figura ni electrones.')
add('S18','limitación','49e9ef3c3296',['n18'],[3],'figura perdida por contrato','Región sombreada entre parábola y coseno.','El recinto solicitado es: (ver figura en la solución original).','Cumple s1; no se conserva dibujo pedido.')
add('S19','baja','2787fc4d640f',['n35','n42','n44'],[5],'corrección/adición menor','n35 resultado v=K[A]·[B]²;n42 4,4×10^-3 sin unidad escrita;n44 corchete sobrante.','n35 cambia K a k;n42 añade mol;n44 elimina corchete,con incidencia.','Normalización razonable matemáticamente,pero no literal estricta. No se identifica cambio de resultado.')
# Añadir resultados exactos e información revisable por entrada; no convertir ratios en certificado semántico.
visual={'25fcf7208b8f','0b7e227a5499','184bfaad518f','1bc800a06e3b','2787fc4d640f','49e9ef3c3296','114bff1bacb1'}
for r in rs:
 r['estado_auditoria']='confirmado';r['comprobacion_manual']=notes[r['documento']];r['hallazgos_auditoria']=[x['id'] for x in findings if x['documento']==r['documento']]
 r['alcance_confirmacion']='Confirma las observaciones descritas; no certifica corrección científica/histórica independiente del solucionario.'
for e,p in zip(es,ps):
 assert all(e[k]==p[k] for k in ('documento','nodo','idioma'))
 fs=[f for f in findings if f['documento']==e['documento'] and e['nodo'] in f['nodos']]
 e['estado_auditoria']='confirmado';e['hallazgos_auditoria']=[f['id'] for f in fs];e['comprobaciones']=['ID exacto en p5','asignación temática y por etiqueta/orden frente a fuente','idioma presente en fuente','rango de página válido','comparación con publicación y r2 si existe']
 e['metodo_contenido']='Lectura visual de las páginas de solución y contraste de texto/fórmulas' if e['documento'] in visual else 'Cotejo léxico de texto completo y revisión manual de atribución, tema y casos divergentes; sin certificación semántica exhaustiva de cada frase'
 e['resultado_revision']='Defectos o límites documentados: '+', '.join(e['hallazgos_auditoria']) if fs else 'Sin divergencia sustancial detectada dentro del alcance descrito'
 e['publicacion']=p
(O/'hallazgos.json').write_text(json.dumps(findings,ensure_ascii=False,indent=2));(O/'registros-revisados.json').write_text(json.dumps(rs,ensure_ascii=False,indent=2));(O/'entradas-revisadas.json').write_text(json.dumps(es,ensure_ascii=False,indent=2))
with (O/'registros.csv').open('w') as f:
 cols=['documento','origen','asignatura','anio','convocatoria','estado_pipeline','contiene_soluciones','entradas','desde','paginas_pdf','estado_auditoria','comprobacion_manual','hallazgos_auditoria'];w=csv.DictWriter(f,fieldnames=cols,extrasaction='ignore');w.writeheader();w.writerows(rs)
with (O/'entradas.csv').open('w') as f:
 cols=['documento','origen','nodo','idioma','pagina','tipo_nodo','estado_auditoria','resultado_revision','metodo_contenido','hallazgos_auditoria'];w=csv.DictWriter(f,fieldnames=cols,extrasaction='ignore');w.writeheader();w.writerows(es)
lines=['# Auditoría de soluciones s1 · 29 de septiembre de 2026','',f'Se revisaron los **25 registros** de `gpt-6-luna__s1` sobre `gpt-6-luna__p5`: **19 oficiales y6 de academia**, todos completed. Hay **10 false**, **15 true**, **218 entradas por nodo** y **227 textos por idioma** (9 nodos bilingües es/va). No hay registros fallidos ni entradas de respuesta vacías. Todos los IDs existen en el árbol p5 y todas las páginas están dentro del PDF; esas dos propiedades no garantizan contenido correcto.','',
'La auditoría encuentra errores matemáticos confirmados en s1, pérdidas anteriores al modelo y pérdidas al publicar. No se puede certificar el conjunto como correcto. Los errores en manuscritos y complementos probabilísticos se comprobaron sobre imágenes del PDF, no sobre OCR.','',
'## Método y alcance real','',
'Lecturas de contrato: README, docs/datos.md y prompt s1. Se abrieron las25 fuentes locales, se inspeccionaron los textos de las secciones de corrección y se confrontaron las218 entradas con el árbol. Para Historia, el cotejo automatizado de texto completo se combinó con revisión manual de encabezados, tema, orden, inicios/finales y divergencias. Eso verifica procedencia y correspondencia de fragmentos; **una similitud léxica alta no prueba exactitud semántica ni exactitud histórica**. No se afirma una segunda corrección académica independiente de cada frase histórica.','',
'Para las21 soluciones manuscritas de Matemáticas2022 se revisaron visualmente las9 páginas. También se inspeccionaron completas las páginas matemáticas de Madrid2019/2021/modelo2026, EHU2026, Química2019 y los dos árboles de Lengua2023. Se revisaron visualmente además las páginas de Historia que sustentan referencias erróneas o de continuación. Se separan erratas de la fuente, errores de transcripción y limitaciones del esquema.','',
'Los estados confirmado/dudoso/no-verificable se refieren a la evidencia de las observaciones. En este lote las25 fuentes están disponibles y las observaciones recogidas son confirmadas; no hay fuentes no-verificables. Ello **no significa25 documentos conformes**. Los CSV/JSON especifican el alcance por documento y por entrada. No se consultó red,API ni modelos adicionales y no se modificaron datos de producción.','',
'## Hallazgos con evidencia','']
for h in findings:
 lines += [f"### {h['id']} · {h['severidad']} · {h['documento']} · {h['tipo']}",'',f"Nodos: {', '.join(h['nodos']) or 'sin nodo en p5'}. Páginas de fuente: {', '.join(map(str,h['paginas_fuente']))}. Estado: {h['estado']}.",'',f"**Fuente:** {h['evidencia_fuente']}",'',f"**Salida:** {h['evidencia_salida']}",'',h['impacto'],'']
lines+=['## Inventario completo de los25 registros','', '| Documento | Origen | Materia/año | Entradas | Comprobación y resultado |','|---|---|---|---:|---|']
for r in rs:lines.append(f"| {r['documento']} | {r['origen']} | {r['asignatura']} {r['anio']} | {r['entradas']} | **Confirmado**. {r['comprobacion_manual']} |")
lines += ['', '## Diferencias con r2 y publicación','',
'En8 de los25 documentos existe un archivo r2 con el mismo ID. Solo3 contienen respuestas comparables: `2787fc4d640f`, `3c134e1125e6`, `49e9ef3c3296`. Se localizaron64 textos s1 con respuesta r2 en el mismo nodo/idioma;15 son idénticos byte a byte. Las49 diferencias restantes se documentan en `publicacion-r2.json`; muchas son saltos de línea, LaTeX y fórmulas equivalentes. El número49 no es una cuenta de errores semánticos.','',
'- Química: r2 y s1 conservan los34 apartados. s1 transforma los equilibrios en tablas Markdown; r2 los serializa como arrays. Las notas sobre nomenclatura anterior a1993 aparecen dentro de respuesta r2 y se excluyen correctamente de s1 como instrucción al corrector. Ambos carecen del dibujo Lewis; s1 cumple su marcador. s1 regulariza K→k y añade mol donde el documento no la imprimió; son cambios de literalidad pequeños.','- Historia2026: s1 n12 incluye el párrafo de Constitución1837/1845, partidos y organización administrativa; r2 lo guarda como criterio y empieza su respuesta en reforma agraria. El contenido s1 está en fuente y corresponde a la misma pregunta compuesta, no es invención. r2 conserva Fernando en la versión valenciana de n13; s1 lo convierte en Ferran.','- Matemáticas EHU: r2 agrupa ecuación de recta con n13 y contexto de gráfica con n18; s1 conserva esos preámbulos en n12/n17 y reparte el resto en hijos. No se considera reasignación incorrecta: son desarrollos comunes del mismo ejercicio. Ninguna de las dos etapas preserva el árbol de probabilidad p1.','',
'**223 de227 textos s1 están publicados idénticos en el nodo correspondiente**, con la misma página, origen y fuente;4 faltan (S06). Por tanto, también se publican los errores S01–S03 y las referencias incorrectas S08. Se verificó el anclaje de apartados usando padre, etiqueta y enunciado del árbol; el banco no conserva IDs en los apartados. No se atribuye a s1 una transformación posterior inexistente.','',
'## Fuente con erratas frente a errores de extracción','',
'El manuscrito Matemáticas2022 sí contiene la derivada incorrecta en A2a, la aproximación0,99 en A4b y la omisión de pañuelos de cuadros en B4a; s1 los conserva y avisa. Son defectos del solucionario. Sin embargo, la raíz cuarta de A2c y el69,5 de A4c están bien en el documento y se alteran al extraer. La barra de complemento de Matemáticas2019 está bien en la fuente y se pierde en s1; su incidencia es falsa.','',
'En1bc800a06e3b el documento contiene pequeñas erratas como determinadod/incompatibled y una notación descuidada de exclusión de valores; s1 las limpia sin avisar, pero los casos,resultados y barras de complemento coinciden. En Historia de academia se conservan afirmaciones discutibles del original: no deben confundirse con invenciones de Luna ni tomarse como validación histórica independiente.','',
'## Figuras y límites del contrato','',
'Hay12 textos con el marcador de figura:8 en Matemáticas academia,2 en Lengua2025,1 Lewis y1 región EHU. Esta ausencia de imagen está ordenada por s1, por lo que es una pérdida funcional del contrato, no una omisión espontánea del modelo. Distinto es el árbol de EHU, que ni siquiera tiene marcador, y los árboles de Lengua2023, que se aplanan en etiquetas sueltas. En la academia se omite además el pequeño esquema del ángulo de A3c sin marcador, aunque se conserva el desarrollo numérico.','',
'## Artefactos y reproducción','',
'`audit.py` abre los25 JSON/PDF, registra SHA256 de fuente, genera `registros.json`, `entradas.json` y contraste léxico de Historia. `compare_stages.py` mapea la publicación por ID de pregunta y padre/etiqueta/enunciado de apartados y compara r2. `finalize.py` agrega las observaciones manuales verificadas y produce los CSV y JSON revisados. Reejecutar en ese orden con `pipeline/.venv/bin/python docs/auditoria-2026-09-29/soluciones/<script>.py`. Ninguno llama al pipeline productivo o a red.','',
'Los archivos `<origen>-<id>.txt` son cuadernos de trabajo locales con árbol,resultado y extracción de texto. Los PNG `<id>-p<n>.png` y dos detalles de manuscrito documentan la revisión visual; no son recortes productivos. `entradas-revisadas.json` tiene una fila por nodo/idioma, texto original, hallazgos,metodología y cotejo de publicación. `registros-revisados.json` y `registros.csv` cubren también los10 false.','']
report='\n'.join(lines)
report=re.sub(r'\b(las|los|de|en|con|por|y|solo|Solo|Hay|hay|esos|esas)(?=\d)',r'\1 ',report)
report=re.sub(r'\b(Historia|Matemáticas|Química|Lengua|EHU|Constitución)(?=20\d\d|19\d\d|18\d\d)',r'\1 ',report)
report=report.replace('3 errores numéricos/léxicos visibles','Errores numéricos/léxicos visibles')
(O/'informe.md').write_text(report);print('written',len(findings),'findings',len(rs),'records',len(es),'texts')
